### ISSUE TITLE
The program freezes and falls off when using the plug-in "FreeMarker"

### ISSUE THREAD

**Issue by aeschli** [dcortes92/vs-freemarker#18] opened 2018-09-17 09:12 UTC
_From @PavelHancharou on June 26, 2018 9:20_

The program freezes and falls off when using the plug-in "FreeMarker"

- VSCode Version: 1.24.1
- OS Version: Win 10 x64
- Plugin for FreeMarker: https://github.com/dcortes92/vs-freemarker
- Version of plugin: 0.0.9

Steps to Reproduce:

1. Open VSC
2. Select Language Mode - FreeMarker (.ftl)
3. Write next text:
${abcdefghijklmnopqrstuvwxyzabcdefj
4. VSCode stop to work

![vscodebug](https://user-images.githubusercontent.com/19645768/41901807-8b85c31a-793a-11e8-8078-de82249da8ea.JPG)

The problem is currectly **with FreeMarker Plugin**, and when there is  **NO closing quote "}"** in the text

_Copied from original issue: Microsoft/vscode#52886_

**Comment by dcortes92** [comment] 2018-09-17 13:52
Hi @aeschli thanks for submitting your issue. Yes I'm able to reproduce this and this is a duplicate of #16. However, I haven't found a way to fix it, I may have to redo the entire language. Thanks for your patience and I apologize for any inconvenience this might have caused.

**Closed as completed by dcortes92** 2018-09-17 13:52 UTC
Labels: duplicate

**Comment by aeschli** [comment] 2018-09-17 14:04
@dcortes92 Thanks for the reply. cc @PavelHancharou
